name: ghar_jagga
description: nepal's real estate.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^5.0.0
  google_maps_flutter: ^2.3.1
  curved_navigation_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
   - assets/images/
   - assets/images/1/
   - assets/images/2/
   - assets/images/3/
   - assets/images/4/
   
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
